[package]
name = "vieille_anar"
version = "1.0.0"
authors = ["Louise de Beaufort <louise@leetchee.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "2.0"
tini = "0.2"
